// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIY-oICtN6moVeCb8GumDMdapzXAPnVVU',
    appId: '1:793280350294:web:f5c40ca5790e06d3b4d3f7',
    messagingSenderId: '793280350294',
    projectId: 'schoolapp-c4747',
    authDomain: 'schoolapp-c4747.firebaseapp.com',
    storageBucket: 'schoolapp-c4747.appspot.com',
    measurementId: 'G-DKLL8WEYZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPhI4TSj0ViiGlwqEns-EvxOg065EYviY',
    appId: '1:793280350294:android:d4d6ed2d543d2784b4d3f7',
    messagingSenderId: '793280350294',
    projectId: 'schoolapp-c4747',
    storageBucket: 'schoolapp-c4747.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn7Xa9dXpwcGbLyVEEToLoOp7mIbXV4AA',
    appId: '1:793280350294:ios:4f82424c4eb10463b4d3f7',
    messagingSenderId: '793280350294',
    projectId: 'schoolapp-c4747',
    storageBucket: 'schoolapp-c4747.appspot.com',
    iosClientId: '793280350294-r9eegssarte1pio3dkbs2kvcovi6iimm.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn7Xa9dXpwcGbLyVEEToLoOp7mIbXV4AA',
    appId: '1:793280350294:ios:72c4a858da0c8fdeb4d3f7',
    messagingSenderId: '793280350294',
    projectId: 'schoolapp-c4747',
    storageBucket: 'schoolapp-c4747.appspot.com',
    iosClientId: '793280350294-l0c764heo683hi4hvrgljrqu7aestor6.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolapp.RunnerTests',
  );
}
